import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="text-2xl">Home 🔥</h1>
        <p>Bem-vindo ao Youtunix! ❤️</p>
        <div className="mt-10">
          <h3 className="text-xl mb-2 font-medium">Tutorial</h3>
          <ul>
            <li>Entre no vídeo no qual você quer fazer o download</li>
            <li>Troque na url, youtube por youtunix</li>
            <li>Escliha a configuração de sua preferência</li>
            <li>Clique em "Download"</li>
          </ul>
        </div>
      </div>
    </>
  )
}
